### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bharatpaliwal-169** [BekBrace/React-Django-Task_Manager#1]
Can anyone help me with how to deploy such full stack applications. I have tried deploying it on heroku as 2 seperate projects 
one for backend and one for frontend 
``.get("https://nayabackendfinal.herokuapp.com/api/tasks/") ``
even changed the link in the app still after the deployment i am unable to get success as everytime it says see 
`` heroku log`` for the error ;((

Please help!! My aim is to learn how to make axios call from a https server into our https frontend . Specificall for django and react. @BekBrace

**Comment by BekBrace** [comment]
Hey Baharat, what's goin on buddy
What is the exact issue stated in the error report ?  
Plus, I recommend - for something simple like a to-do app - to deploy through one host only instead of two separate folders; at least this will avoid the trouble with CORS and access permissions

**Comment by bharatpaliwal-169** [comment]
Can you refer me a properly stated document on  how to deploy a full stack app on heroku like with django backend and react frontend , any blog, video link or anything from where i can really getting going with the deployment , as u know django have a lot of stuff to be modified before moving to production and getting it up n running on server.

Any help would be appreciated, Thanks in advance.

**Comment by BekBrace** [comment]
There's a good article on dev.to which I believe can bring help to the subject:
https://dev.to/shakib609/deploy-your-django-react-js-app-to-heroku-2bck
